apiVersion: v1
kind: Secret
metadata:
  name: __CI_PROJECT_NAME__-app
  namespace: __CI_PROJECT_NAMESPACE__
type: Opaque
stringData:
  .env: |
    APP_NAME=__CI_PROJECT_NAME__
    APP_ENV=local
    APP_KEY=base64:/1KwPKuNvr533+EJJQYHbppAgsE4f8eJ7t5evaoDd10=
    APP_DEBUG=true
    APP_API=__CI_PROJECT_NAME__-api
    DB_CONNECTION=mysql
    DB_HOST=__CI_PROJECT_NAME__-mysql
    DB_PORT=3306
    DB_DATABASE=laravel
    DB_USERNAME=laravel
    DB_PASSWORD="kR$9EfQmqcPuGv!U8VAZ"