apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __CI_PROJECT_NAME__-mysql
  namespace: __CI_PROJECT_NAMESPACE__
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes