apiVersion: v1
kind: Secret
metadata:
  name: __CI_PROJECT_NAME__-mysql
  namespace: __CI_PROJECT_NAMESPACE__
type: Opaque
data:
  ROOT_PASSWORD: RUROV3JNNERxSzJ6M0o5YWZGbzI0ZHRp
  #pM5mD2kF4cL4kW4lV8uQ6hB7kC4iM6kT