apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kZXZvcHMudGkuaG93ZXN0LmJlIjp7InVzZXJuYW1lIjoia3ViZXJuZXRlcyIsInBhc3N3b3JkIjoieFNlV3JLdmszb3JzVng2eHhCdEwiLCJlbWFpbCI6Inl2ZXMra3ViZXJuZXRlcy1ob3dlc3RAc3RhcmZpc2suY29tIiwiYXV0aCI6ImEzVmlaWEp1WlhSbGN6cDRVMlZYY2t0MmF6TnZjbk5XZURaNGVFSjBUQT09In19fQ==
kind: Secret
metadata:  
  name: howest-docker-registry
  namespace: __CI_PROJECT_NAMESPACE__
type: kubernetes.io/dockerconfigjson
